# Change these first
owner: thwiki # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: THBWiki
    url: https://thwiki.cc/%E9%A6%96%E9%A1%B5
  - name: THBWiki CD Site
    url: https://cd.thwiki.cc/
  - name: THBWiki Tools
    url: https://tool.thwiki.cc/
  - name: THBVote
    url: http://touhou.vote/
  - name: Touhou Group
    url: https://touhou.group/
  - name: Nyasama
    url: https://bbs.nyasama.com/
  - name: MineCraft Gensoukyo
    url: https://gensoukyo.moe/
  - name: Gensoukyo Map
    url: https://map.thwiki.cc/
  - name: Dream
    url: https://dream.thwiki.cc/
  - name: THBWiki Calendar Api
    url: https://calendar.thwiki.cc/
  - name: Lyrics
    url: https://lyrics.thwiki.cc/
  - name: Omake
    url: https://omake.thwiki.cc/
  - name: Patch
    url: https://patch.thwiki.cc/
  - name: Avatar
    url: https://avatar.thwiki.cc/thwikicc_wiki_default_l.jpg
  - name: Touhou98 Font
    url: https://touhou98.touhou.moe/
  - name: Akyuu
    url: https://akyuu.touhou.moe/
  - name: TohoMoe
    url: https://toho.moe/
  - name: Wiki Redirect
    url: https://thbwiki.cc/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://static.thwiki.cc/banner/banner_b1@2x.png
  name: THBWiki Status
  introTitle: "**[THBWiki](https://thwiki.cc/THBWiki:%E5%85%B3%E4%BA%8E) Sites** Uptime Monitor"
  introMessage: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
