# Change these first
owner: thwiki # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: THBWiki
    url: https://thwiki.cc/%E9%A6%96%E9%A1%B5
  - name: THBWiki CD Site
    url: https://cd.thwiki.cc/
  - name: THBWiki Tools
    url: https://tool.thwiki.cc/
  - name: THBVote
    url: http://touhou.vote/
  - name: Nyasama
    url: https://bbs.nyasama.com/
  - name: MineCraft Gensoukyo
    url: https://gensoukyo.moe/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/thwiki/tools/master/src/assets/banner_b1.png
  name: THBWiki Status
  introTitle: "**[THBWiki](https://thwiki.cc/THBWiki:%E5%85%B3%E4%BA%8E) Sites** Uptime Monitor"
  introMessage: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
